backend:
  name: github
  repo: Mrk81245/sito-Trentino
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "contenuti/articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"
      - label: "Contenuto"
        name: "body"
        widget: "markdown"
      - label: "Immagine"
        name: "image"
        widget: "image"
        required: false
